### ISSUE TITLE
after 2.3.x version, input method candidate word window don't follow cursor!

### ISSUE THREAD

**Issue by andong307** [android/android-studio-poet#139]
after 2.3.x version, input method candidate word window don't follow cursor!

**Comment by borisf** [comment]
I am sorry, I don;t understand can you attach a screenshot with steps, please

**Comment by NikitaKozlov** [comment]
I don't understand as well. A video would be even better! Thank you.

**Comment by andong307** [comment]
please see the picture below.
![question](https://user-images.githubusercontent.com/4253975/50573480-a1997d80-0e0f-11e9-86ff-71cd7023c5bc.png)

**Comment by NikitaKozlov** [comment]
I'm sorry to say that, but this repo is a wrong place to report bugs for Android Studio. This is a repo for Android Studio Poet, a separate helper tool. Please check this: https://developer.android.com/studio/report-bugs, it explains how to report bugs for Android Studio.

**Comment by borisf** [comment]
Closing the bug
