### ISSUE TITLE
More than 250 modules causes an exception in Gradle when project is opened

### ISSUE THREAD

**Issue by srmurguia** [android/android-studio-poet#20]
The way the project's build.gradle file is created causes all the modules to be included in a single include command. This causes more than 250 parameters to be passed and generate an exception in Gradle. A workaround is to split that line manually into multiple include commands (with no more than 250 modules) after the project was created.

**Comment by srmurguia** [comment]
It is not build.gradle, it is on settings.gradle file. Sorry for the confusion.

**Comment by borisf** [comment]
@NikitaKozlov what are the ways we could solve this, could it be by adding a custom Gradle task that breaks into multiple include commands ?

**Comment by srmurguia** [comment]
I think the simplest way is to split it in multiple include commands on the same settings.gradle file

**Comment by NikitaKozlov** [comment]
Mb like this? https://github.com/borisf/java-generator/pull/21

**Comment by srmurguia** [comment]
Yes, that will do it.

**Comment by borisf** [comment]
Thanks all!
