### ISSUE TITLE
Configure versions of kotlin, gradle, android gradle plugin

### ISSUE THREAD

**Issue by jmfayard** [android/android-studio-poet#40]
Hello, it would super practical if those things were configurable with a sensible default

```
com.android.tools.build:gradle:3.0.1
kotlin_version=1.1.60
distributionUrl=https\://services.gradle.org/distributions/gradle-4.2.1-all.zip
```

**Comment by NikitaKozlov** [comment]
That would be covered with new input format, please check https://github.com/borisf/android-studio-poet/pull/36
