### ISSUE TITLE
Mocking framework

### ISSUE THREAD

**Issue by oleksiyp** [android/android-studio-poet#62]
Hi,

hope find you well with this cold call.

I am an author of [mocking framework for Kotlin](http://mockk.io)

I see you are using mockito-kotlin.

I just want you to be aware that there is solution that fully supports Kotlin and ask to try it in your new/current projects.

I can help you if you answer to this issue.

Thanks and please star [it](https://github.com/oleksiyp/mockk)

**Comment by borisf** [comment]
@NikitaKozlov

**Comment by oleksiyp** [comment]
This is not an issue itself. I see no reply and dont want to hang it forever. Still it is in history/mail

**Comment by borisf** [comment]
We are still checking, you know Xmas time ...

On Mon, Dec 25, 2017 at 8:11 PM, Oleksiy Pylypenko <notifications@github.com

**Comment by oleksiyp** [comment]
np as I said still its possible to communicate. Thanks for response. Merry Xmas :christmas_tree:  :christmas_tree:  :christmas_tree:

**Comment by oleksiyp** [comment]
@borisf Do you realize that's spam message?

To balance things in nature I opened real issue https://issuetracker.google.com/issues/71045344 for Android Studio
