### ISSUE TITLE
Add documentation for image generation

### ISSUE THREAD

**Issue by borisf** [android/android-studio-poet#98]
Add an MD file to explain the image generation from https://github.com/android/android-studio-poet/pull/95

**Comment by borisf** [comment]
One good way could be generating an html based report with the following structure:

Info from dependencies.dot
Gradle color [format](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_configurations_graph)
Info from dependencies.png

Start from [here](https://github.com/android/android-studio-poet/blob/master/src/main/kotlin/com/google/androidstudiopoet/generators/SourceModuleGenerator.kt#L80)

**Comment by srmurguia** [comment]
#100 only adds the md file, but is not generating the report yet.

**Comment by borisf** [comment]
This is OK for now, lets see how the things will go and if needed we ca add HTML generation
